DROP TABLE IF EXISTS hobbies;
DROP TABLE IF EXISTS phone;
DROP TABLE IF EXISTS person;
 
CREATE TABLE person (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  age INT NOT NULL
);


CREATE TABLE hobbies (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  p_id INT NOT NULL
);

CREATE TABLE phone (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  ph_no INT NOT NULL,
  p_id INT NOT NULL
);